- name:  configure postgresql node 
  hosts: _ansible_nodejs
  become: true 
  tasks: 
    - name:  update the node 
      yum:
        name: '*'
        state: latest 
    - name: uninstall old versions 
      yum:
        name: "{{ item }}" 
        state: removed 
      loop:
        - docker 
        - docker-client 
        - docker-client-latest 
        - docker-common 
        - docker-latest 
        - docker-latest-logrotate 
        - docker-logrotate 
        - docker-engine   
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest 
    - name: add docker repo 
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/dcoker-ce.repo
    - name: install docker 
      package:
        name: docker-ce
        state: present 
    - name: install pip 
      package:
        name: python3-pip
        state: present 
    - name: install docker sdk 
      pip:
        name: docker
    - name: add ec2-user to docker group 
      user: 
        name: ec2-user 
        groups: docker
        append: yes
    - name: start docker service 
      systemd:
        name: docker
        enable: yes
        state: started 
    - name: create build directory 
      file: 
        path: /home/ec2-user/nodejs
        state: directory 
        owner: root 
        group: root 
        mode: "0755"
    - name: copy files to the nodejs node 
      copy:
        src: /home/ec2-user/ansible/ansible-Project/nodejs/server/
        dest: /home/ec2-user/nodejs
    - name: copy the dockerfile
      copy:
        src: /home/ec2-user/ansible/ansible-Project/nodejs/Dockerfile
        dest: /home/ec2-user/nodejs
    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=ilker_nodejs' && docker stop ilker_nodejs && docker rm -fv ilker_nodejs && docker image rm -f flamentes/nodejs || echo 'Not Found'"
    - name: build container image 
      docker_image:
        name: flamentes/nodejs
        build: 
          path: /home/ec2-user/nodejs
        source: build 
        state: present 
    - name: create nodejs docker container
      docker_container:
        name: ilker_nodejs
        image: flamentes/postgre
        state: started 
        ports:
          - "5000:5000"
      register: container_info
    - name: print container_info
      debug:
        var: container_info