- name:  configure postgresql node 
  hosts: _ansible_postgresql
  become: true 
  tasks: 
    - name:  update the node 
      yum:
        name: '*'
        state: latest 
    - name: uninstall old versions 
      yum:
        name: "{{ item }}" 
        state: removed 
      loop:
        - docker 
        - docker-client 
        - docker-client-latest 
        - docker-common 
        - docker-latest 
        - docker-latest-logrotate 
        - docker-logrotate 
        - docker-engine   
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest 
    - name: add docker repo 
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/dcoker-ce.repo
    - name: install docker 
      package:
        name: docker-ce
        state: present 
    - name: install pip 
      package:
        name: python3-pip
        state: present 
    - name: install docker sdk 
      pip:
        name: docker
    - name: add ec2-user to docker group 
      user: 
        name: ec2-user 
        groups: docker
        append: yes
    - name: start docker service 
      systemd:
        name: docker
        enable: yes
        state: started 
    - name: create build directory 
      file: 
        path: /home/ec2-user/postgresql
        state: directory 
        owner: root 
        group: root 
        mode: "0755"
    - name: copy the sql script 
      copy:
        src: /home/ec2-user/ansible/ansible-Project/postgres/init.sql
        dest: /home/ec2-user/postgresql
    - name: copy the dockerfile 
      copy:
        src: /home/ec2-user/ansible/ansible-Project/postgres/Dockerfile
        dest: /home/ec2-user/postgresql
    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=ilker_postgre' && docker stop ilker_postgre && docker rm -fv ilker_postgre && docker image rm -f flamentes/postgre || echo 'Not Found'"
    - name: build container image 
      docker_image:
        name: flamentes/postgre
        build: 
          path: /home/ec2-user/postgresql
        source: build 
        state: present 
    - name: create postgresql docker container
      docker_container:
        name: ilker/postgre
        image: flamentes_postgre
        state: started 
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "Pp123456789"
        volumes: 
          - /db-data:/var/lib/postgresql/data
      register: container_info
    - name: print container_info
      debug:
        var: container_info